const scenes = [
  {name:'雾起',en:'THE AWAKENING',title:'山河未醒',verse:'天地无言，\n只听见一场梦的呼吸。',file:'01-dawn.webp',duration:24,x:58,y:50,mode:'mist'},
  {name:'听雨',en:'WHISPERS OF RAIN',title:'一川烟雨',verse:'雨落青山外，\n人行水墨间。',file:'02-rain.webp',duration:22,x:45,y:50,mode:'rain'},
  {name:'行舟',en:'DRIFTING INTO STILLNESS',title:'一叶渡千山',verse:'把尘世留在岸上，\n随一江春水，去往远方。',file:'03-river.webp',duration:24,x:55,y:55,mode:'spark'},
  {name:'入林',en:'THE HIDDEN PATH',title:'竹深不知处',verse:'风穿过竹叶，\n时光便慢了下来。',file:'04-bamboo.webp',duration:22,x:52,y:50,mode:'leaf'},
  {name:'观瀑',en:'THE MOUNTAIN SINGS',title:'万壑有回声',verse:'看飞流写下长诗，\n听群山回应心跳。',file:'05-waterfall.webp',duration:23,x:48,y:45,mode:'rain'},
  {name:'逐霞',en:'THE LAST LIGHT',title:'落日照归途',verse:'走过万水千山，\n才读懂一缕人间烟火。',file:'06-sunset.webp',duration:23,x:62,y:50,mode:'spark'},
  {name:'望月',en:'BENEATH ONE MOON',title:'千里共清辉',verse:'此刻，万籁俱寂。\n月光替故人，照亮来路。',file:'07-moon.webp',duration:22,x:52,y:40,mode:'star'},
  {name:'归心',en:'EVERY JOURNEY IS A RETURN',title:'山河入梦',verse:'山河在眼底，\n故乡在心上。',file:'08-return.webp',duration:20,x:50,y:50,mode:'mist'}
];
let total=0;scenes.forEach(s=>{s.start=total;total+=s.duration});
const $=s=>document.querySelector(s), frames=[...document.querySelectorAll('.frame')], reduced=matchMedia('(prefers-reduced-motion: reduce)');
let position=0,playing=false,started=false,ended=false,active=-1,front=0,last=0,muted=true,audio,master,nextNote=0,noteIndex=0;
const images=scenes.map(s=>{const im=new Image();im.src=`assets/${s.file}`;return im});
const nav=$('.chapter-nav');scenes.forEach((s,i)=>{const b=document.createElement('button');b.textContent=`0${i+1} ${s.name}`;b.setAttribute('aria-label',`跳转到第${i+1}章：${s.name}`);b.onclick=()=>{begin(false);position=s.start;ended=false;render(true)};nav.append(b)});
function format(v){return `${String(Math.floor(v/60)).padStart(2,'0')}:${String(Math.floor(v%60)).padStart(2,'0')}`}
function render(force=false){const index=Math.min(7,scenes.findIndex(s=>position<s.start+s.duration));const s=scenes[index<0?7:index],i=index<0?7:index,p=(position-s.start)/s.duration;
if(i!==active||force){if(i!==active){front=1-front;const im=frames[front].querySelector('img');im.src=images[i].src;im.style.objectPosition=`${s.x}% ${s.y}%`;frames[front].classList.add('active');frames[1-front].classList.remove('active');active=i;$('#chapter').textContent=`第${['一','二','三','四','五','六','七','八'][i]}幕 · ${s.en}`;$('#scene-title').textContent=s.title;$('#scene-verse').textContent=s.verse;$('#caption').textContent=`${String(i+1).padStart(2,'0')} / ${s.name}`;$('#caption-en').textContent=s.en;[...nav.children].forEach((n,k)=>{n.classList.toggle('current',k===i);n.setAttribute('aria-current',k===i?'step':'false')})}}
if(!reduced.matches){const dir=i%2?1:-1;frames[front].querySelector('img').style.transform=`scale(${1.06+p*.10}) translate(${dir*(p-.5)*2.5}%,${(p-.5)*-1.8}%)`;$('.mist-a').style.transform=`translateX(${Math.sin(position*.025)*9}%)`;$('.mist-b').style.transform=`translateX(${Math.cos(position*.035)*-12}%)`}
$('#verse').classList.toggle('visible',started&&!ended&&p>.14&&p<.77);$('#elapsed').textContent=format(position);$('#seek').value=position;document.documentElement.style.setProperty('--progress',`${position/180*100}%`);$('#end').hidden=!ended;$('#pause').textContent=playing?'Ⅱ':'▷';$('#pause').setAttribute('aria-label',playing?'暂停':'播放');}
function begin(withSound=true){started=true;document.body.classList.add('started');ended=false;playing=true;if(position>=180)position=0;if(withSound&&muted)toggleSound();last=performance.now();render(true)}
function setPlaying(v){playing=v;if(audio&&master)master.gain.setTargetAtTime(muted||!playing?0:.25,audio.currentTime,.3);render()}
function restart(){position=0;ended=false;begin(false)}
$('#start').onclick=()=>begin();$('#pause').onclick=()=>{if(!started||ended)begin(false);else setPlaying(!playing)};$('#restart').onclick=restart;$('#again').onclick=restart;
$('#seek').oninput=e=>{if(!started)begin(false);position=+e.target.value;ended=position>=180;if(ended)setPlaying(false);render(true)};
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('#film').requestFullscreen)await $('#film').requestFullscreen();else notice('当前浏览器不支持全屏，请横屏欣赏')}catch{notice('当前浏览器暂不支持全屏')}};
function notice(text){$('#notice').textContent=text;$('#notice').classList.add('show');setTimeout(()=>$('#notice').classList.remove('show'),3000)}
function setupAudio(){const AC=window.AudioContext||window.webkitAudioContext;if(!AC){notice('当前浏览器不支持合成音频');return false}audio=new AC();master=audio.createGain();master.gain.value=0;master.connect(audio.destination);const delay=audio.createDelay(3),feedback=audio.createGain();delay.delayTime.value=.72;feedback.gain.value=.26;delay.connect(feedback);feedback.connect(delay);delay.connect(master);audio.echo=delay;return true}
async function toggleSound(){try{if(!audio&&!setupAudio())return;await audio.resume();muted=!muted;master.gain.setTargetAtTime(muted||!playing?0:.25,audio.currentTime,.4);$('#sound').textContent=muted?'声 ×':'声 ≋';$('#sound').setAttribute('aria-label',muted?'开启声音':'静音');$('#sound').setAttribute('aria-pressed',String(!muted))}catch{notice('声音暂不可用，请再次轻触声音按钮')}}
$('#sound').onclick=toggleSound;
function score(){if(!audio||muted||!playing)return;master.gain.setTargetAtTime(.25,audio.currentTime,.5);if(audio.currentTime<nextNote)return;nextNote=audio.currentTime+1.6+(active%3)*.25;const notes=[146.83,164.81,196,220,246.94,293.66,329.63,392];const melodies=[[0,2,4,3,2,0,1,2],[4,6,5,4,2,3,1,0],[0,3,4,7,6,4,2,3]];const n=melodies[Math.floor(active/3)%3][noteIndex++%8];const t=audio.currentTime;for(const [ratio,level] of [[1,.32],[2,.075],[3,.025]]){const osc=audio.createOscillator(),g=audio.createGain();osc.type='sine';osc.frequency.value=notes[n]*ratio;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(level,t+.035);g.gain.exponentialRampToValueAtTime(.0001,t+5);osc.connect(g);g.connect(master);g.connect(audio.echo);osc.start(t);osc.stop(t+5.1)}if(noteIndex%4===1){const o=audio.createOscillator(),g=audio.createGain();o.frequency.value=[73.415,98,110,82.405][Math.floor(active/2)];g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.14,t+2);g.gain.linearRampToValueAtTime(0,t+8);o.connect(g);g.connect(master);o.start(t);o.stop(t+8)}}
const canvas=$('#atmosphere'),ctx=canvas.getContext('2d');let w,h;const particles=Array.from({length:75},(_,i)=>({x:Math.random(),y:Math.random(),z:.2+Math.random()*.8,seed:i}));function resize(){w=innerWidth;h=$('#film').clientHeight;canvas.width=w;canvas.height=h}addEventListener('resize',resize);resize();
function draw(){ctx.clearRect(0,0,w,h);if(reduced.matches)return;const mode=scenes[Math.max(0,active)].mode;for(const p of particles){const t=position;let x=(p.x+t*.003*p.z)%1*w,y=(p.y+t*(mode==='rain'?.17:.008)*p.z)%1*h;ctx.globalAlpha=mode==='rain'?.13:.12+.18*Math.sin(t+p.seed)**2;ctx.strokeStyle='#d9e4e1';ctx.fillStyle=mode==='spark'?'#e6c998':'#e2e8df';if(mode==='rain'){ctx.beginPath();ctx.moveTo(x,y);ctx.lineTo(x-4,y+17*p.z);ctx.stroke()}else if(mode==='leaf'){ctx.save();ctx.translate(x,y);ctx.rotate(t*.3+p.seed);ctx.fillRect(0,0,2,7*p.z);ctx.restore()}else if(mode!=='mist'){ctx.beginPath();ctx.arc(x,y,(mode==='star'?1:1.7)*p.z,0,7);ctx.fill()}}ctx.globalAlpha=1}
function tick(now){const delta=Math.min((now-last)/1000,.1);last=now;if(playing){position=Math.min(180,position+delta);if(position>=180){ended=true;setPlaying(false)}render();score()}draw();requestAnimationFrame(tick)}
addEventListener('keydown',e=>{if(e.target.matches('button,input'))return;if(e.code==='Space'){e.preventDefault();$('#pause').click()}if(e.key==='m')$('#sound').click();if(e.key==='ArrowRight'){position=Math.min(180,position+5);render(true)}if(e.key==='ArrowLeft'){position=Math.max(0,position-5);render(true)}});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)setPlaying(false)});
images[0].onerror=()=>notice('画面加载失败，请检查网络后刷新');render(true);requestAnimationFrame(tick);
