import {Landscape} from './world.js';
import {FilmScore} from './score.js';
import {DURATION,CHAPTERS,chapterAt,clamp} from './timeline.js';
const $=s=>document.querySelector(s),score=new FilmScore();
let world,playing=false,started=false,ended=false,position=0,muted=true,last=performance.now(),previewTime=9,qualityMode=0,preparing=false,lockCamera=false;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const params=new URLSearchParams(location.search),testMode=params.has('qa');
const fmt=t=>`${String(Math.floor(t/60)).padStart(2,'0')}:${String(Math.floor(t%60)).padStart(2,'0')}`;
function notice(s){$('#notice').textContent=s;$('#notice').classList.add('show');clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('#notice').classList.remove('show'),3500)}
function ui(){const i=chapterAt(position),c=CHAPTERS[i];$('#caption').textContent=`0${i+1} / ${c.name}`;$('#caption-en').textContent=c.en;$('#elapsed').textContent=fmt(position);$('#seek').value=position;document.documentElement.style.setProperty('--progress',`${position/DURATION*100}%`);$('#pause').textContent=playing?'Ⅱ':'▷';$('#pause').setAttribute('aria-label',playing?'暂停':'播放');$('#sound').textContent=preparing?'声 …':muted?'声 ×':'声 ≋';$('#sound').setAttribute('aria-label',muted?'开启声音':'静音');$('#sound').setAttribute('aria-pressed',String(!muted));document.body.classList.toggle('paused',!playing);document.body.classList.toggle('ink-intro',started&&position<9);document.body.classList.toggle('ended',ended||(started&&position>=175));$('#end').hidden=!(ended||(started&&position>=175));[...$('.chapter-nav').children].forEach((b,j)=>{b.classList.toggle('current',i===j);b.setAttribute('aria-current',i===j?'step':'false')});$('#title-kicker').textContent=c.en;$('#title-main').textContent=c.title;$('#title-sub').textContent=c.sub;const local=position-c.start;$('#title-card').classList.toggle('visible',started&&!ended&&i>0&&local>3&&local<8);}
async function sound(){if(preparing)return;try{preparing=true;ui();await score.enable();muted=!muted;score.setMuted(muted);score.update(position,playing)}catch(e){console.error(e);notice('声音暂时未开启，请再轻触声音按钮')}finally{preparing=false;ui()}}
function begin(withSound=true){if(!world)return;started=true;ended=false;document.body.classList.add('started');if(position>=180)position=0;playing=true;last=performance.now();if(withSound&&muted)sound();if(reduced)notice('已保留实时动画。可随时暂停，或拖动时间轴逐帧欣赏。');ui();wake();}
function setPlaying(v){if(!started){begin(false);return}playing=v;last=performance.now();score.update(position,playing);ui();wake()}
function seek(t){position=clamp(t,0,180);ended=position>=180;if(ended)playing=false;score.update(position,playing);ui();world?.render(position,false,lockCamera);wake()}
function restart(){position=0;begin(false);score.update(position,playing);world.render(position)}
for(const c of CHAPTERS){const b=document.createElement('button');b.textContent=c.name;b.title=`${fmt(c.start)} ${c.en}`;b.setAttribute('aria-label',`跳到 ${c.name}`);b.onclick=()=>{if(!started)begin(false);seek(c.start)};$('.chapter-nav').append(b)}
$('#start').onclick=()=>begin();$('#pause').onclick=()=>ended?restart():setPlaying(!playing);$('#restart').onclick=restart;$('#again').onclick=restart;$('#sound').onclick=sound;$('#seek').oninput=e=>{if(!started){started=true;document.body.classList.add('started')}seek(+e.target.value)};
$('#quality').onclick=()=>{qualityMode=(qualityMode+1)%3;const q=[world.mobile?.8:1,1,.6][qualityMode];world.setQuality(q);$('#quality').textContent=`画质 · ${['自动','精细','流畅'][qualityMode]}`;world.render(started?position:previewTime,!started);notice(['自动适配画质','精细画质','流畅画质，保留全部三维动画'][qualityMode])};
$('#fullscreen').onclick=async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else if($('#film').requestFullscreen)await $('#film').requestFullscreen();else notice('请将设备横屏欣赏')}catch{notice('当前浏览器暂不支持全屏，请横屏欣赏')}};
let idleTimer;function wake(){document.body.classList.remove('idle');clearTimeout(idleTimer);idleTimer=setTimeout(()=>{if(playing&&!testMode)document.body.classList.add('idle')},3800)}
addEventListener('pointermove',wake,{passive:true});addEventListener('pointerdown',wake,{passive:true});addEventListener('keydown',e=>{if(e.target.matches('input'))return;if(e.code==='Space'){e.preventDefault();ended?restart():setPlaying(!playing)}if(e.key.toLowerCase()==='m')sound();if(e.key==='ArrowRight'){e.preventDefault();if(!started)begin(false);seek(position+5)}if(e.key==='ArrowLeft'){e.preventDefault();if(!started)begin(false);seek(position-5)}wake()});
addEventListener('resize',()=>{world?.resize();world?.render(started?position:previewTime,!started,lockCamera)});document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)setPlaying(false)});
$('#world').addEventListener('webglcontextlost',e=>{e.preventDefault();playing=false;score.update(position,false);notice('图形连接中断，正在等待恢复。');ui()});$('#world').addEventListener('webglcontextrestored',()=>location.reload());
let lastUI=0,frames=0,frameSum=0;function frame(now){requestAnimationFrame(frame);const dt=Math.max(0,(now-last)/1000);last=now;if(!world)return;if(playing){position=Math.min(180,position+dt);if(position>=180){playing=false;ended=true;ui()}}else if(!started&&!reduced)previewTime+=dt*.22;
 if(playing||!started){world.render(started?position:previewTime,!started,lockCamera);frames++;frameSum+=dt;if(qualityMode===0&&frames===150&&frameSum/frames>.042&&world.quality>.65){world.setQuality(.65)}}score.update(position,playing);if(now-lastUI>100){ui();lastUI=now}}
try{world=new Landscape($('#world'));world.render(previewTime,true);$('#start').disabled=false;$('#start-label').innerHTML='入 画<small>BEGIN THE JOURNEY</small>';window.__film={seek(t){if(!started){started=true;document.body.classList.add('started')}seek(t)},play(){setPlaying(true)},pause(){setPlaying(false)},setCameraLock(v){lockCamera=v},render(t){seek(t)},get state(){return {position,playing,started,ended,muted,preparing,scoreReady:score.ready,stats:world.stats}},world,score};if(testMode){const box=document.createElement('div');box.id='qa-status';box.style='position:absolute;left:12px;top:110px;z-index:50;background:#001a20c9;color:#e5eddc;font:10px monospace;padding:8px;max-width:340px;white-space:pre-wrap';const lock=document.createElement('button');lock.textContent='Lock camera';lock.style='display:block;padding:8px;background:#254f50';lock.onclick=()=>{lockCamera=!lockCamera;lock.textContent=lockCamera?'Unlock camera':'Lock camera'};box.append(lock);const status=document.createElement('span');box.append(status);document.body.append(box);setInterval(()=>status.textContent='\n'+JSON.stringify({t:+position.toFixed(2),playing,audio:score.ready,boat:world.stats?.boat.map(v=>+v.toFixed(2)),oar:+world.stats?.oar.toFixed(2),mist:+world.stats?.mist.toFixed(2),camera:world.stats?.camera.map(v=>+v.toFixed(2)),quality:world.quality}),500);if(params.has('t')){started=true;document.body.classList.add('started');seek(+params.get('t'));}}
ui();requestAnimationFrame(frame)}catch(e){console.error(e);$('#error').hidden=false;$('#start-label').textContent='画面初始化失败'}
