import * as THREE from './vendor/three.module.js';
import {cameraAt,atmosphereAt,range,clamp,mix} from './timeline.js';
const V=THREE.Vector3;
function batchDirect(group){
 const byMaterial=new Map();group.updateMatrix();
 for(const child of [...group.children]){if(!child.isMesh)continue;child.updateMatrix();const geom=child.geometry.index?child.geometry.toNonIndexed():child.geometry.clone();geom.applyMatrix4(child.matrix);const list=byMaterial.get(child.material)||[];list.push(geom);byMaterial.set(child.material,list);group.remove(child);}
 for(const [material,gs] of byMaterial){const geo=new THREE.BufferGeometry();for(const key of ['position','normal','uv']){if(!gs.every(g=>g.attributes[key]))continue;const size=gs.reduce((n,g)=>n+g.attributes[key].array.length,0),arr=new Float32Array(size);let off=0;for(const g of gs){arr.set(g.attributes[key].array,off);off+=g.attributes[key].array.length;}geo.setAttribute(key,new THREE.BufferAttribute(arr,gs[0].attributes[key].itemSize));}group.add(new THREE.Mesh(geo,material));for(const g of gs)g.dispose();}
}
let seed=219;
function rnd(){seed=(seed*1664525+1013904223)>>>0;return seed/4294967296}
const noise=(x,y,z=0)=>Math.sin(x*1.27+Math.cos(y*.83+z))*Math.cos(y*1.41+Math.sin(z*.72+x*.57));
const GLSL=`
float hash(vec3 p){p=fract(p*.1031);p+=dot(p,p.yzx+33.33);return fract((p.x+p.y)*p.z);}
float noise(vec3 p){vec3 i=floor(p),f=fract(p);f=f*f*(3.-2.*f);return mix(mix(mix(hash(i),hash(i+vec3(1,0,0)),f.x),mix(hash(i+vec3(0,1,0)),hash(i+vec3(1,1,0)),f.x),f.y),mix(mix(hash(i+vec3(0,0,1)),hash(i+vec3(1,0,1)),f.x),mix(hash(i+vec3(0,1,1)),hash(i+vec3(1,1,1)),f.x),f.y),f.z);}
float fbm(vec3 p){float v=0.;v+=.5*noise(p);p=p*2.03+17.1;v+=.25*noise(p);p=p*2.01+7.3;v+=.125*noise(p);return v;}
`;
const vertex=`varying vec3 vWorld;varying vec3 vNormal;varying vec3 vEye;varying vec2 vUv;void main(){vUv=uv;vec4 w=modelMatrix*vec4(position,1.);vWorld=w.xyz;vNormal=normalize(mat3(modelMatrix)*normal);vEye=cameraPosition-w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`;
export class Landscape{
 constructor(canvas){
 this.mobile=innerWidth<760;this.quality=this.mobile?.8:1;this.renderer=new THREE.WebGLRenderer({canvas,antialias:!this.mobile,alpha:false,powerPreference:'high-performance'});this.renderer.setPixelRatio(Math.min(devicePixelRatio,this.mobile?1.25:1.5));this.renderer.outputColorSpace=THREE.SRGBColorSpace;this.scene=new THREE.Scene();this.scene.background=new THREE.Color('#bacbc0');this.camera=new THREE.PerspectiveCamera(48,1,.3,2100);this.camera.position.set(0,50,250);
 this.u={uTime:{value:0},uNight:{value:0},uStorm:{value:0},uSunset:{value:0},uReveal:{value:1},uResolve:{value:0},uFog:{value:new THREE.Color('#bbcec0')},uRockTexture:{value:new THREE.TextureLoader().load('assets/01-dawn.webp')}};this.u.uRockTexture.value.colorSpace=THREE.NoColorSpace;
 this.rockMaterial=new THREE.ShaderMaterial({uniforms:{...this.u},vertexShader:vertex.replace("void main(){", "uniform float uReveal;void main(){").replace("vec4 w=modelMatrix*vec4(position,1.);", "vec3 p=position;p.y*=smoothstep(.08,.88,uReveal);vec4 w=modelMatrix*vec4(p,1.);"),fragmentShader:`${GLSL} varying vec3 vWorld;varying vec3 vNormal;varying vec3 vEye;uniform float uNight,uStorm,uSunset,uReveal;uniform vec3 uFog;uniform sampler2D uRockTexture;void main(){
 vec3 p=vWorld;vec3 n=normalize(vNormal);float brush=fbm(vec3(p.x*.14,p.y*.11,p.z*.14));float stria=fbm(vec3(p.x*.55,p.y*.22,p.z*.55));float cracks=smoothstep(.53,.65,stria);float fine=noise(p*vec3(1.1,.62,1.1));float lit=clamp(dot(n,normalize(vec3(-.6,.8,.3)))*.5+.48,.05,1.);float upward=smoothstep(.05,.78,n.y);float mottled=fbm(p*.047);vec3 ink=vec3(.019,.09,.13);vec3 jade=vec3(.085,.32,.38);vec3 malachite=vec3(.24,.43,.32);vec3 rock=mix(ink,jade,lit*.78+brush*.18);rock=mix(rock,malachite,upward*.6+mottled*.14);vec3 blend=pow(abs(n),vec3(3.));blend/=max(dot(blend,vec3(1.)),.001);vec2 warp=vec2(brush,mottled)*.12;vec3 tx=texture2D(uRockTexture,(1.-abs(fract(p.yz*.0075+warp)*2.-1.))*vec2(.28,.40)+vec2(.035,.02)).rgb;vec3 ty=texture2D(uRockTexture,(1.-abs(fract(p.xz*.0075+warp)*2.-1.))*vec2(.28,.40)+vec2(.035,.02)).rgb;vec3 tz=texture2D(uRockTexture,(1.-abs(fract(p.xy*.0075+warp)*2.-1.))*vec2(.28,.40)+vec2(.035,.02)).rgb;vec3 grainColor=tx*blend.x+ty*blend.y+tz*blend.z;float pigment=dot(grainColor,vec3(.3,.5,.2));rock*=.58+pigment*1.35;rock+=grainColor*vec3(.075,.055,.028);rock*=.83+brush*.25;float sunLit=pow(max(0.,dot(n,normalize(vec3(-.8,.75,.4)))),2.);rock=mix(rock,vec3(.48,.43,.25),sunLit*(.09+upward*.23));rock*=1.-cracks*.34;float cun=sin(p.y*1.6+noise(p*.13)*12.);rock*=1.-smoothstep(.82,.97,cun)*.12;rock+=vec3(.12,.11,.054)*smoothstep(.48,.63,brush)*lit*.7;rock-=vec3(.04)*smoothstep(.57,.83,fine);float mineral=fbm(p*vec3(.7,.43,.7));rock=mix(rock,vec3(.10,.29,.36),smoothstep(.52,.63,mineral)*.3);rock+=vec3(.12,.10,.035)*smoothstep(.66,.74,mineral)*upward;float edge=pow(1.-abs(dot(n,normalize(vEye))),4.);rock*=1.-edge*.22;rock=mix(rock,rock*vec3(1.32,.96,.68)+vec3(.055,.025,0.)*lit,uSunset*.8);rock=mix(rock,rock*vec3(.32,.46,.63),uNight*.88);rock*=1.-uStorm*.2;float dist=length(vEye);float fog=1.-exp(-dist*.0020);fog=clamp(fog+exp(-max(p.y,0.)*.038)*.14,0.,.95);vec3 col=mix(rock,uFog,fog);gl_FragColor=vec4(col,1.);}`});
 this.makeSky();this.makeMountains();this.makeTrees();this.makeWater();this.makeMist();this.makeBoat();this.makeWaterfall();this.makeBirds();this.makeRibbons();this.makeRain();this.makePost();this.resize();
 }
 makeSky(){
 this.sky=new THREE.Mesh(new THREE.SphereGeometry(1300,32,16),new THREE.ShaderMaterial({side:THREE.BackSide,depthWrite:false,uniforms:this.u,vertexShader:vertex,fragmentShader:`${GLSL} varying vec3 vWorld;uniform float uTime,uNight,uStorm,uSunset;uniform sampler2D uRockTexture;void main(){vec3 d=normalize(vWorld-cameraPosition);float h=smoothstep(-.05,.65,d.y);vec3 low=vec3(.80,.82,.73),hi=vec3(.28,.45,.49);low=mix(low,vec3(.89,.65,.39),uSunset);hi=mix(hi,vec3(.29,.43,.49),uSunset);low=mix(low,vec3(.17,.27,.32),uNight);hi=mix(hi,vec3(.014,.057,.097),uNight);vec3 c=mix(low,hi,h);vec3 skyArt=texture2D(uRockTexture,vec2(clamp(d.x*.55+.5,0.,1.),clamp(.78+d.y*.65,0.,1.))).rgb;c=mix(c,skyArt,smoothstep(.025,.09,d.y)*(1.-smoothstep(.25,.35,d.y))*(1.-uNight)*.35);float clouds=fbm(vec3(d.x*4.+uTime*.006,d.y*8.,d.z*4.));c+=vec3(.11)*smoothstep(.37,.67,clouds)*(1.-h*.55)*(1.-uNight*.75);c=mix(c,c*vec3(.58,.7,.76),uStorm*.6);vec3 sunDir=normalize(vec3(-.22,.20,-.8));float s=dot(d,sunDir);c+=vec3(1.,.59,.24)*pow(max(s,0.),100.)*uSunset*.28;float moon=dot(d,normalize(vec3(.10,.32,-1.)));c+=vec3(.75,.84,.77)*(1.-fbm(d*150.)*.23)*smoothstep(.9988,.9992,moon)*uNight;float stars=step(.9986,hash(floor(d*700.)))*smoothstep(.18,.65,d.y);c+=stars*uNight*.65;gl_FragColor=vec4(c,1.);}`}));this.scene.add(this.sky);
 }
 peak(x,z,r,h,s,stretch=1){
 const nr=this.mobile?38:54,ny=this.mobile?25:36;const pos=[],uv=[],ind=[];
 for(let j=0;j<=ny;j++){let v=j/ny;for(let i=0;i<=nr;i++){let a=i/nr*Math.PI*2;let cr=Math.pow(1-v,.44+.24*(.5+.5*Math.sin(s*2.7)))*(.84+.12*Math.sin(v*6+s));let ribs=1+.10*Math.sin(a*7+s+v*1.8)+.06*Math.cos(a*13+s-v*4)+.04*Math.sin(a*29+v*12);let rough=1+.10*noise(Math.cos(a)*4+s,v*12,Math.sin(a)*4)+.045*noise(Math.cos(a)*13,v*23+s,Math.sin(a)*13);let radius=r*cr*ribs*rough;let xx=Math.cos(a)*radius+Math.sin(v*3+s)*r*.34*v*v,zz=Math.sin(a)*radius*stretch+Math.cos(v*4+s)*r*.24*v*v;let yy=h*v+(Math.sin(a*4+s)+Math.sin(a*7+s*2))*.022*h*Math.sin(v*Math.PI);pos.push(x+xx,yy-4,z+zz);uv.push(i/nr,v);if(j<ny&&i<nr){let q=j*(nr+1)+i;ind.push(q,q+nr+1,q+1,q+1,q+nr+1,q+nr+2)}}}
 const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('uv',new THREE.Float32BufferAttribute(uv,2));g.setIndex(ind);g.computeVertexNormals();const m=new THREE.Mesh(g,this.rockMaterial);this.scene.add(m);return m;
 }
 makeMountains(){
 this.peaks=[];
 for(let row=0;row<8;row++){const z=250-row*133;for(let side of [-1,1]){const x=side*(120+rnd()*45)+Math.sin(z*.005)*25;const r=45+rnd()*42,h=55+rnd()*150;this.peaks.push(this.peak(x,z,r,h,rnd()*20,1.25));this.peaks.push(this.peak(x+side*(100+rnd()*100),z-40,80+rnd()*70,125+rnd()*170,rnd()*30,1.1));}}
 for(let i=0;i<12;i++){this.peaks.push(this.peak((i-5.5)*100,-1050-rnd()*170,80+rnd()*60,170+rnd()*220,rnd()*20,1));}
 // A foreground spur crosses the camera's path, revealing the concealed river behind it.
 this.peak(-75,144,42,99,6,1.35);this.peak(79,-187,49,170,12,.8);
 // A waterfall-cut cliff with an irregular stone lip.
 this.peak(-115,-480,65,173,18,.9);this.peak(-48,-503,53,198,28,1.15);
 }
 makeTrees(){
 this.trees=[];const material=new THREE.MeshBasicMaterial({color:'#143b36'});this.treeMaterial=material;
 const canopyMaterial=new THREE.ShaderMaterial({uniforms:this.u,vertexShader:vertex,fragmentShader:`${GLSL} varying vec3 vWorld,vNormal,vEye;uniform vec3 uFog;uniform float uNight,uSunset;void main(){float light=clamp(dot(normalize(vNormal),normalize(vec3(-.5,1.,.3)))*.5+.5,0.,1.);float fleck=noise(vWorld*2.5);vec3 c=mix(vec3(.025,.10,.09),vec3(.15,.29,.19),light*.7+fleck*.3);c=mix(c,c*vec3(1.3,.95,.6),uSunset*.5);c*=1.-uNight*.58;c=mix(c,uFog,1.-exp(-length(vEye)*.0025));gl_FragColor=vec4(c,1.);}`});this.canopyMaterial=canopyMaterial;
 const treeLocations=[[-71,149,77],[-112,226,132],[101,142,100],[75,-178,139],[-84,-355,72],[-133,-470,150],[69,-63,89],[-154,-77,126],[140,-354,140],[-46,-516,178],[92,32,125],[-178,-253,162]];
 for(let k=0;k<treeLocations.length;k++){const [x,z,y]=treeLocations[k],tree=new THREE.Group();const rocks=this.scene.children.filter(m=>m.material===this.rockMaterial);const summitRock=rocks[[0,2,5,8,11,15,18,22,25,30,44,46][k]];const sp=summitRock.geometry.attributes.position;let high=0;for(let si=1;si<sp.count;si++)if(sp.getY(si)>sp.getY(high))high=si;tree.position.set(sp.getX(high),sp.getY(high)-.65,sp.getZ(high));const size=3.5+rnd()*4;const trunkPoints=[new V(0,0,0),new V(-.25*size,.45*size,0),new V(-.1*size,.9*size,.1*size),new V(-.32*size,1.55*size,0)];const trunk=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(trunkPoints),12,.07*size,5,false),material);tree.add(trunk);
 for(let j=0;j<6;j++){const h=size*(.55+j*.17),side=j%2?1:-1,len=size*(.74-j*.045);const start=new V(-.15*size,h,0),tip=new V(side*len,h+size*.13,(rnd()-.5)*size*.8);tree.add(new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3([start,new V(tip.x*.55,h+size*.22,tip.z*.5),tip]),6,.033*size,4),material));for(let q=0;q<3;q++){let canopy=new THREE.Mesh(new THREE.SphereGeometry(1,15,8),canopyMaterial);const cp=canopy.geometry.attributes.position;for(let cv=0;cv<cp.count;cv++){const nx=cp.getX(cv),ny=cp.getY(cv),nz=cp.getZ(cv);const rr=1+noise(nx*12,ny*12,nz*12)*.19;cp.setXYZ(cv,nx*rr,ny*rr,nz*rr);}canopy.geometry.computeVertexNormals();canopy.scale.set(size*(.43+rnd()*.15),size*(.11+rnd()*.065),size*(.27+rnd()*.13));canopy.position.copy(tip).add(new V((q-1)*size*.27,rnd()*size*.1,(rnd()-.5)*size*.25));tree.add(canopy);}}
 batchDirect(tree);this.scene.add(tree);this.trees.push({tree,phase:rnd()*6});}
 }
 makeWater(){
 this.reflectTarget=new THREE.WebGLRenderTarget(this.mobile?512:1024,this.mobile?256:512,{type:THREE.UnsignedByteType});this.reflectCamera=new THREE.PerspectiveCamera();
 this.waterMaterial=new THREE.ShaderMaterial({uniforms:{...this.u,uReflection:{value:this.reflectTarget.texture},uTextureMatrix:{value:new THREE.Matrix4()},uBoat:{value:new V()}},vertexShader:`varying vec3 vWorld;varying vec3 vEye;varying vec4 vReflect;uniform float uTime;uniform mat4 uTextureMatrix;void main(){vec3 p=position;p.z+=sin(p.x*.045+uTime*.6)*.12+sin(p.y*.065-uTime*.9)*.08;vec4 w=modelMatrix*vec4(p,1.);vWorld=w.xyz;vEye=cameraPosition-w.xyz;vReflect=uTextureMatrix*w;gl_Position=projectionMatrix*viewMatrix*w;}`,fragmentShader:`${GLSL} varying vec3 vWorld,vEye;varying vec4 vReflect;uniform sampler2D uReflection;uniform vec3 uFog,uBoat;uniform float uTime,uNight,uStorm,uSunset;void main(){vec2 p=vWorld.xz;float wave=sin(p.x*.12+p.y*.13-uTime*1.4)*.5+sin(p.x*.3-p.y*.17+uTime*.9)*.23+sin(p.y*.8+uTime*2.7)*.08;vec2 distort=vec2(noise(vec3(p*.037,uTime*.1))-.5,wave*.25)*(.003+uStorm*.003);vec2 uv=vReflect.xy/vReflect.w;vec3 refl=texture2D(uReflection,clamp(uv+distort,.002,.998)).rgb;vec3 base=mix(vec3(.07,.24,.25),vec3(.08,.13,.20),uNight);base=mix(base,vec3(.27,.26,.17),uSunset*.6);float fres=pow(1.-clamp(normalize(vEye).y,0.,1.),2.);vec3 c=mix(base,refl,.35+fres*.36);float lines=pow(max(0.,sin(p.y*.68+wave*4.+noise(vec3(p*.15,0.))*7.+uTime*.75)),24.);float patches=fbm(vec3(p*.016,uTime*.035));c+=vec3(.19,.28,.23)*lines*smoothstep(.44,.66,patches)*(.05+.1*fres);float impact=length((p-vec2(-78.,-389.))*vec2(1.,1.3));float ring=pow(max(0.,sin(impact*.9-uTime*4.)),8.)*exp(-impact*.045);c+=vec3(.16,.20,.16)*ring*.42;vec2 b=p-uBoat.xz;float trail=step(0.,b.y)*exp(-b.y*.028)*exp(-abs(abs(b.x)-b.y*.17)*1.4);float foam=trail*(.5+.5*sin(b.y*1.6-uTime*6.));c+=vec3(.36,.41,.32)*foam*.5;float dist=length(vEye);c=mix(c,uFog,1.-exp(-dist*.0014));gl_FragColor=vec4(c,1.);}`});this.water=new THREE.Mesh(new THREE.PlaneGeometry(2400,2500,90,90),this.waterMaterial);this.water.rotation.x=-Math.PI/2;this.water.position.set(0,0,-350);this.scene.add(this.water);
 }
 makeMist(){
 this.mistMaterial=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,uniforms:this.u,vertexShader:vertex,fragmentShader:`${GLSL} varying vec2 vUv;varying vec3 vWorld;uniform float uTime,uNight,uStorm,uSunset;uniform vec3 uFog;void main(){vec2 p=vUv*2.-1.;float shape=exp(-p.x*p.x*2.4-p.y*p.y*5.2);float n=fbm(vec3(vUv.x*5.+uTime*.017,vUv.y*3.,vWorld.z*.02));float a=shape*smoothstep(.17,.66,n)*.19;gl_FragColor=vec4(uFog+vec3(.06),a);}`});this.mists=[];
 for(let i=0;i<30;i++){const m=new THREE.Mesh(new THREE.PlaneGeometry(330+rnd()*300,40+rnd()*40),this.mistMaterial);m.position.set((rnd()-.5)*420,12+rnd()*70,270-i*46);this.scene.add(m);this.mists.push({m,x:m.position.x,z:m.position.z,phase:rnd()*6});}
 }
 makeBoat(){
 const boat=new THREE.Group(),dark=new THREE.MeshBasicMaterial({color:'#24352b'}),gold=new THREE.MeshBasicMaterial({color:'#967744'}),robe=new THREE.MeshBasicMaterial({color:'#aa502f'});
 const shape=new THREE.Shape();shape.moveTo(0,-7);shape.bezierCurveTo(1.7,-4,1.9,3,0,7);shape.bezierCurveTo(-1.9,3,-1.7,-4,0,-7);const hull=new THREE.Mesh(new THREE.ExtrudeGeometry(shape,{depth:.8,bevelEnabled:true,bevelSize:.2,bevelThickness:.3,bevelSegments:2,steps:1}),dark);hull.rotation.x=-Math.PI/2;boat.add(hull);
 for(let z=-4;z<5;z+=1){const b=new THREE.Mesh(new THREE.BoxGeometry(2.25,.10,.18),gold);b.position.set(0,.9,z);boat.add(b);}
 const canopy=new THREE.Mesh(new THREE.CylinderGeometry(1.35,1.35,3.6,14,1,true,-Math.PI/2,Math.PI),gold);canopy.rotation.set(-Math.PI/2,0,0);canopy.position.set(0,1.2,1);boat.add(canopy);
 const body=new THREE.Mesh(new THREE.ConeGeometry(.45,1.6,8),robe);body.position.set(0,1.7,-3.8);boat.add(body);const head=new THREE.Mesh(new THREE.SphereGeometry(.28,10,8),dark);head.position.set(0,2.7,-3.8);boat.add(head);const hat=new THREE.Mesh(new THREE.ConeGeometry(.8,.28,15),gold);hat.position.set(0,3,-3.8);boat.add(hat);
 const oar=new THREE.Mesh(new THREE.CylinderGeometry(.065,.09,7.3,6),gold);oar.position.set(1.3,1.5,-3.8);oar.rotation.z=.55;boat.add(oar);this.oar=oar;const rimPts=[];for(let j=0;j<=30;j++){const aa=j/30*Math.PI*2;rimPts.push(new V(Math.sin(aa)*1.36*Math.pow(Math.abs(Math.sin(aa)),.20),.95,Math.cos(aa)*6.7));}boat.add(new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(rimPts,true),55,.055,4,true),gold));for(let rz=-.8;rz<=2.8;rz+=.6){const arc=[];for(let a=0;a<=12;a++){const aa=a/12*Math.PI;arc.push(new V(Math.cos(aa)*1.38,1.2+Math.sin(aa)*1.38,rz));}boat.add(new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3(arc),12,.035,3),dark));}boat.remove(oar);batchDirect(boat);boat.add(oar);this.boat=boat;this.scene.add(boat);
 }
 makeWaterfall(){
 const wallGeo=new THREE.BoxGeometry(39,155,55,16,45,8);const wp=wallGeo.attributes.position;for(let i=0;i<wp.count;i++){const x=wp.getX(i),y=wp.getY(i),z=wp.getZ(i);const vv=(y+77.5)/155;wp.setXYZ(i,x*(1+(1-vv)*.9)+noise(x*.12,y*.06,4)*1.3,y+(Math.sin(x*.14)+Math.sin(z*.2))*3*vv,z+noise(x*.2,y*.09,7)*1.6);}wallGeo.computeVertexNormals();const wall=new THREE.Mesh(wallGeo,this.rockMaterial);wall.position.set(-78,75,-422);this.scene.add(wall);
 this.fall=new THREE.Mesh(new THREE.PlaneGeometry(13,154,20,60),new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,uniforms:this.u,vertexShader:`varying vec2 vUv;varying vec3 vWorld;uniform float uTime;void main(){vUv=uv;vec3 p=position;p.x*=.77+uv.y*.23;p.x+=sin(uv.y*12.+uTime*1.2)*.35;p.z+=sin(uv.y*17.-uTime*3.)*.3;vec4 w=modelMatrix*vec4(p,1.);vWorld=w.xyz;gl_Position=projectionMatrix*viewMatrix*w;}`,fragmentShader:`${GLSL} varying vec2 vUv;varying vec3 vWorld;uniform float uTime,uNight;uniform vec3 uFog;void main(){float er=noise(vec3(vUv.y*18.-uTime*1.8,1.,1.))*.09;float edges=smoothstep(er,.22,vUv.x)*smoothstep(1.-er,.78,vUv.x);float streams=fbm(vec3(vUv.x*38.+sin(vUv.y*25.+uTime*6.),vUv.y*25.+uTime*9.,1.));float fine=sin(vUv.x*190.+sin(vUv.y*12.+uTime*4.)*2.)*.5+.5;float a=edges*(.28+.72*streams+.14*fine)*smoothstep(0.,.045,vUv.y)*smoothstep(1.,.984,vUv.y);vec3 c=mix(vec3(.78,.86,.77),vec3(.38,.57,.59),uNight);c=mix(c,uFog,clamp(distance(cameraPosition,vWorld)*.0007,0.,.6));gl_FragColor=vec4(c,a);}`}));this.fall.position.set(-78,76,-391);this.fall.rotation.y=.1;this.scene.add(this.fall);
 const pos=[],speeds=[];for(let i=0;i<550;i++){pos.push((rnd()-.5)*24,rnd()*160,(rnd()-.5)*16);speeds.push(rnd());}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(pos,3));g.setAttribute('aSeed',new THREE.Float32BufferAttribute(speeds,1));this.spray=new THREE.Points(g,new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms:this.u,vertexShader:`attribute float aSeed;uniform float uTime;varying float vAlpha;void main(){vec3 p=position;float fall=mod(p.y-uTime*(22.+aSeed*13.)+10000.,160.);p.y=fall;p.x*=1.+pow(1.-fall/160.,5.)*3.;vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=clamp((100.+aSeed*110.)/-mv.z,1.,7.);vAlpha=.25+pow(1.-fall/160.,5.)*.5;}`,fragmentShader:`varying float vAlpha;void main(){float a=1.-length(gl_PointCoord-.5)*2.;gl_FragColor=vec4(.8,.88,.8,max(0.,a)*vAlpha);}`}));this.spray.position.set(-78,1,-389);this.scene.add(this.spray);
 }
 makeBirds(){
 this.birds=[];const white=new THREE.MeshBasicMaterial({color:'#e7e4ce'}),black=new THREE.MeshBasicMaterial({color:'#18383c'}),red=new THREE.MeshBasicMaterial({color:'#9c3e26'});this.birdWhite=white;
 for(let i=0;i<9;i++){const b=new THREE.Group(),body=new THREE.Mesh(new THREE.SphereGeometry(1,9,7),white);body.scale.set(.44,.48,1.45);b.add(body);const neck=new THREE.Mesh(new THREE.TubeGeometry(new THREE.CatmullRomCurve3([new V(0,.2,-.7),new V(0,.65,-1.5),new V(0,.72,-2.2)]),9,.14,5),white);b.add(neck);const beak=new THREE.Mesh(new THREE.ConeGeometry(.1,.9,5),black);beak.rotation.x=-Math.PI/2;beak.position.set(0,.72,-2.6);b.add(beak);const crown=new THREE.Mesh(new THREE.SphereGeometry(.14,7,5),red);crown.position.set(0,.87,-2.1);b.add(crown);const wings=[];for(let s of [-1,1]){const wing=new THREE.Group();let sh=new THREE.Shape();sh.moveTo(0,0);sh.bezierCurveTo(s*1.1,-.55,s*2.8,-.75,s*4.6,.4);sh.bezierCurveTo(s*3,1.25,s*1.3,1.4,0,.6);const mesh=new THREE.Mesh(new THREE.ShapeGeometry(sh,8),white);mesh.rotation.x=-Math.PI/2;wing.add(mesh);for(let f=0;f<5;f++){const feather=new THREE.Mesh(new THREE.ConeGeometry(.17,1.65,5),black);feather.rotation.set(Math.PI/2,0,s*(.3+f*.15));feather.position.set(s*(2.75+f*.31),0,.55+f*.11);wing.add(feather);}batchDirect(wing);b.add(wing);wings.push(wing);}for(let s of [-1,1]){const leg=new THREE.Mesh(new THREE.CylinderGeometry(.035,.035,1.65,4),black);leg.rotation.x=Math.PI/2;leg.position.set(s*.16,-.2,1.6);b.add(leg);}batchDirect(b);this.scene.add(b);this.birds.push({b,wings,phase:rnd()*6,scale:.40+rnd()*.20});}
 }
 makeRibbons(){
 const N=180;this.ribbons=[];for(let j=0;j<5;j++){const g=new THREE.BufferGeometry(),p=new Float32Array((N+1)*2*3),uv=new Float32Array((N+1)*2*2),ind=[];for(let i=0;i<=N;i++){uv[i*4]=i/N;uv[i*4+1]=0;uv[i*4+2]=i/N;uv[i*4+3]=1;if(i<N){let q=i*2;ind.push(q,q+1,q+2,q+1,q+3,q+2)}}g.setAttribute('position',new THREE.BufferAttribute(p,3));g.setAttribute('uv',new THREE.BufferAttribute(uv,2));g.setIndex(ind);const mat=new THREE.ShaderMaterial({transparent:true,depthWrite:false,side:THREE.DoubleSide,uniforms:{...this.u,uIndex:{value:j}},vertexShader:vertex,fragmentShader:`${GLSL} varying vec2 vUv;uniform float uTime,uIndex;void main(){float edge=sin(vUv.y*3.14159);float brush=noise(vec3(vUv.x*65.,vUv.y*8.,uIndex*10.));float a=edge*smoothstep(.12,.62,brush)*sin(vUv.x*3.14159)*.75;vec3 c=mix(vec3(.026,.11,.14),vec3(.48,.46,.23),step(3.5,uIndex));gl_FragColor=vec4(c,a);}`});const m=new THREE.Mesh(g,mat);m.frustumCulled=false;this.scene.add(m);this.ribbons.push({m,p,N,j});}
 }
 makeRain(){const ps=[],seeds=[];for(let i=0;i<1500;i++){ps.push((rnd()-.5)*500,rnd()*250,(rnd()-.5)*800);seeds.push(rnd());}const g=new THREE.BufferGeometry();g.setAttribute('position',new THREE.Float32BufferAttribute(ps,3));g.setAttribute('aSeed',new THREE.Float32BufferAttribute(seeds,1));this.rain=new THREE.Points(g,new THREE.ShaderMaterial({transparent:true,depthWrite:false,uniforms:this.u,vertexShader:`uniform float uTime;attribute float aSeed;varying float vS;void main(){vec3 p=position;p.y=mod(p.y-uTime*(80.+aSeed*40.)+20000.,250.);p.x+=sin(uTime*.1)*25.;p.z-=150.;vec4 mv=modelViewMatrix*vec4(p,1.);gl_Position=projectionMatrix*mv;gl_PointSize=clamp(650./-mv.z,1.,12.);vS=aSeed;}`,fragmentShader:`uniform float uStorm;varying float vS;void main(){vec2 p=gl_PointCoord-.5;float a=exp(-p.x*p.x*250.)*(1.-abs(p.y)*2.);gl_FragColor=vec4(.72,.81,.78,a*uStorm*.35);}`}));this.scene.add(this.rain);}
 makePost(){
 this.target=new THREE.WebGLRenderTarget(1,1);this.postScene=new THREE.Scene();this.postCamera=new THREE.OrthographicCamera(-1,1,1,-1,0,1);this.postMat=new THREE.ShaderMaterial({uniforms:{...this.u,uImage:{value:this.target.texture},uResolution:{value:new THREE.Vector2()},uAspect:{value:1}},vertexShader:`varying vec2 vUv;void main(){vUv=uv;gl_Position=vec4(position.xy,0.,1.);}`,fragmentShader:`${GLSL} varying vec2 vUv;uniform sampler2D uImage;uniform vec2 uResolution;uniform float uTime,uReveal,uResolve,uAspect;void main(){vec2 uv=vUv;vec3 c=texture2D(uImage,uv).rgb;float grain=hash(vec3(uv*uResolution,0.))-.5;c+=grain*.024;vec2 p=uv-.5;p.x*=uAspect;float feather=fbm(vec3(p*7.,0.));float ink=length(p)*(1.+feather*.24);float reveal=smoothstep(uReveal*2.5-.08,uReveal*2.5+.11,ink);vec3 paper=vec3(.87,.865,.79)+grain*.025;float opening=(1.-uReveal);c=mix(c,paper,reveal*opening);float dropR=.035+pow(clamp(uTime/3.,0.,1.),2.)*.20;float drop=1.-smoothstep(dropR*.85,dropR*1.1+feather*.02,length(p)+noise(vec3(p*35.,uTime*.5))*.012);c=mix(c,vec3(.035,.10,.105),drop*(1.-smoothstep(1.2,4.2,uTime)));float resolve=smoothstep(uResolve*1.9-.25,uResolve*1.9+.3,ink);c=mix(c,mix(paper,c,resolve),smoothstep(0.,.02,uResolve));gl_FragColor=vec4(c,1.);}`});this.postScene.add(new THREE.Mesh(new THREE.PlaneGeometry(2,2),this.postMat));
 }
 setQuality(q){this.quality=q;this.resize()}
 resize(){const w=innerWidth,h=innerHeight;this.renderer.setSize(w,h,false);this.camera.aspect=w/h;this.camera.updateProjectionMatrix();const ratio=Math.min(devicePixelRatio,this.mobile?1.25:1.5)*this.quality;this.target.setSize(Math.round(w*ratio),Math.round(h*ratio));this.postMat.uniforms.uResolution.value.set(w*ratio,h*ratio);this.postMat.uniforms.uAspect.value=w/h;}
 render(t,preview=false,lockCamera=false){
 const a=atmosphereAt(t);this.u.uTime.value=t;this.u.uNight.value=a.night;this.u.uStorm.value=a.storm;this.u.uSunset.value=a.sunset;this.u.uReveal.value=preview?1:a.reveal;this.u.uResolve.value=preview?0:a.resolve;
 const fog=new THREE.Color().setRGB(.73,.77,.70).lerp(new THREE.Color().setRGB(.72,.59,.39),a.sunset*.65).lerp(new THREE.Color().setRGB(.07,.14,.19),a.night*.94);fog.multiplyScalar(1-a.storm*.27);this.u.uFog.value.copy(fog);
 const camera=cameraAt(t);if(!lockCamera){this.camera.position.fromArray(camera.position);this.camera.lookAt(new V().fromArray(camera.look));this.camera.fov=camera.fov+(innerWidth<innerHeight?10:0);this.camera.updateProjectionMatrix();}
 this.sky.position.copy(this.camera.position);
 // Boat, water, oar, mist and trees advance independently of the camera.
 const bz=151-t*3.65,bx=Math.sin(bz*.005)*21;this.boat.position.set(bx,.48+Math.sin(t*1.55)*.09,bz);this.boat.rotation.set(Math.sin(t*1.2)*.012,-Math.cos(bz*.005)*.085,Math.sin(t*.9)*.024);this.oar.rotation.z=.46+Math.sin(t*1.25)*.21;this.oar.rotation.x=Math.sin(t*1.25)*.3;this.waterMaterial.uniforms.uBoat.value.copy(this.boat.position);
 for(const {tree,phase} of this.trees){tree.scale.y=preview?1:Math.max(.001,range(t,5,12));tree.rotation.z=Math.sin(t*.62+phase)*(.007+a.storm*.016);tree.rotation.x=Math.cos(t*.53+phase)*.005;}
 this.treeMaterial.color.set('#143b36').lerp(new THREE.Color('#10242b'),a.night*.8);
 for(const {m,x,z,phase} of this.mists){m.position.x=x+Math.sin(t*.035+phase)*45;m.position.z=z+Math.cos(t*.02+phase)*13;m.quaternion.copy(this.camera.quaternion);}
 for(let i=0;i<this.birds.length;i++){const {b,wings,phase,scale}=this.birds[i];const hero=range(t,121,127)*(1-range(t,151,157));if(hero>.01){const p=(t-126);b.position.set(-6+p*5.8+(i%3-1)*11,105+Math.sin(p*.14+phase)*6+Math.floor(i/3)*4,-52-p*10+Math.floor(i/3)*15);b.scale.setScalar(scale*(i===0?1.3:1)*range(t,121,128));}else{b.position.set(Math.sin(t*.027+phase)*150,140+Math.sin(t*.06+phase)*12,-190-(i%5)*90-t*.8);b.scale.setScalar(scale*.8);}b.rotation.y=-.5+Math.sin(t*.1+phase)*.12;b.rotation.z=Math.sin(t*.17+phase)*.12;const flap=Math.sin(t*2.7+phase)*.4+.06;wings[0].rotation.z=flap;wings[1].rotation.z=-flap;}
 this.birdWhite.color.set('#e7e4ce').lerp(new THREE.Color('#7b989a'),a.night*.7);
 for(const {m,p,N,j} of this.ribbons){m.visible=t>98&&t<130;const growth=range(t,98,111)*(1-range(t,127,130));const morph=range(t,117,127);if(m.visible){for(let i=0;i<=N;i++){const u=i/N,theta=u*Math.PI*2.5-t*.19+j*.47;const rad=(22+u*110)*growth;const center=new V(Math.cos(theta)*rad,28+u*170,-260+Math.sin(theta)*rad);const birdX=-6+(t-126)*5.8+(j%3-1)*11,birdY=105+Math.floor(j/3)*4,birdZ=-52-(t-126)*10+Math.floor(j/3)*15;center.lerp(new V(birdX+(u-.5)*18,birdY+Math.sin(u*Math.PI)*3,birdZ+Math.pow((u-.5)*2,2)*2),morph);const w=Math.sin(u*Math.PI)*mix(3+j*.55,1.15,morph)*growth;for(let s=0;s<2;s++){let ix=(i*2+s)*3;p[ix]=center.x;p[ix+1]=center.y+(s?1:-1)*w;p[ix+2]=center.z+(s?1:-1)*w*.3;}}m.geometry.attributes.position.needsUpdate=true;}}
 this.rain.visible=a.storm>.01;
 // Real-time planar reflection: actual hidden geometry is rendered from a mirrored camera.
 this.camera.updateMatrixWorld();this.reflectCamera.copy(this.camera);this.reflectCamera.position.y=-this.camera.position.y;const target=new V();this.camera.getWorldDirection(target);target.add(this.camera.position);target.y=-target.y;this.reflectCamera.up.set(0,-1,0);this.reflectCamera.lookAt(target);this.reflectCamera.updateMatrixWorld();const textureMatrix=this.waterMaterial.uniforms.uTextureMatrix.value;textureMatrix.set(.5,0,0,.5,0,.5,0,.5,0,0,.5,.5,0,0,0,1);textureMatrix.multiply(this.reflectCamera.projectionMatrix);textureMatrix.multiply(this.reflectCamera.matrixWorldInverse);
 this.water.visible=false;this.renderer.setRenderTarget(this.reflectTarget);this.renderer.render(this.scene,this.reflectCamera);this.water.visible=true;this.renderer.setRenderTarget(this.target);this.renderer.render(this.scene,this.camera);this.renderer.setRenderTarget(null);this.renderer.render(this.postScene,this.postCamera);
 this.stats={time:t,camera:this.camera.position.toArray(),boat:this.boat.position.toArray(),oar:this.oar.rotation.x,mist:this.mists[0].m.position.x,drawCalls:this.renderer.info.render.calls,triangles:this.renderer.info.render.triangles,quality:this.quality};
 }
}
